### ISSUE TITLE
Add selected stuff from IPython examples live coded 

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810-2017-10#7]
```
Last login: Sat Oct 21 10:01:53 on ttys000
mbp-danny:~ danielmsheehan$ cd Github/pratt-savi-810-2017-10/
mbp-danny:pratt-savi-810-2017-10 danielmsheehan$ ls
README.md		class-2017-11-04.ipynb	img
class-2017-10-21.ipynb	class-2017-11-11.ipynb	resources.ipynb
class-2017-10-28.ipynb	env
mbp-danny:pratt-savi-810-2017-10 danielmsheehan$ source env/bin/activate
(env) mbp-danny:pratt-savi-810-2017-10 danielmsheehan$ ipython
Python 2.7.13 (default, Sep  6 2017, 18:33:14) 
Type "copyright", "credits" or "license" for more information.

IPython 5.5.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: 1 + 1
Out[1]: 2

In [2]: %paste
  File "<tokenize>", line 8
    if type(i) == int or type(i) == float:
    ^
IndentationError: unindent does not match any outer indentation level


In [3]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
  myNewList = []
  print myList
  for i in myList:
    print i
    if type(i) == int or type(i) == float:
      myNewList.append(i)
      print i
    else:
      print i
    return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
-74.0059
-74.0059
[-74.0059]

In [4]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
  myNewList = []
  print myList
  for i in myList:
    print i
    if type(i) == int or type(i) == float:
      print i
      myNewList.append(i)
      print i
    else:
      print i
    return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
-74.0059
-74.0059
-74.0059
[-74.0059]

In [5]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
  myNewList = []
  print myList
  for i in myList:
    print type(i)
    if type(i) == int or type(i) == float:
      print i
      myNewList.append(i)
      print i
    else:
      print i
    return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
<type 'float'>
-74.0059
-74.0059
[-74.0059]

In [6]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
        myNewList = []
        print myList
        for i in myList:
                print type(i)
        if type(i) == int or type(i) == float:
                print i
                myNewList.append(i)
                print i
        else:
                print i
        return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
<type 'float'>
<type 'float'>
<type 'int'>
<type 'float'>
<type 'str'>
potato
[]

In [7]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
        myNewList = []
        print myList
        for i in myList:
                print type(i)
                if type(i) == int or type(i) == float:
                        print i
                        myNewList.append(i)
                        print i
                else:
                        print i
                return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
<type 'float'>
-74.0059
-74.0059
[-74.0059]

In [8]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
        myNewList = []
        print myList
        for i in myList:
                print type(i)
                if type(i) == int or type(i) == float:
                        print i
                        myNewList.append(i)
                        print i
                else:
                        print i
                return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
<type 'float'>
-74.0059
-74.0059
[-74.0059]

In [9]: %paste
myCoords = [-74.0059, 40.7127, 32, 40.650002, 'potato']

def returnNumericListItems(myList):
        myNewList = []
        print myList
        for i in myList:
                print type(i)
                if type(i) == int or type(i) == float:
                        print i
                        myNewList.append(i)
                        print i
                else:
                        print i
        return myNewList

print returnNumericListItems(myCoords)

## -- End pasted text --
[-74.0059, 40.7127, 32, 40.650002, 'potato']
<type 'float'>
-74.0059
-74.0059
<type 'float'>
40.7127
40.7127
<type 'int'>
32
32
<type 'float'>
40.650002
40.650002
<type 'str'>
potato
[-74.0059, 40.7127, 32, 40.650002]

In [10]: for i in range(10):
    ...:     print i
    ...:     
0
1
2
3
4
5
6
7
8
9

In [11]: for i in range(10):
    ...:     
    ...:     
    ...:     print i
    ...:     
0
1
2
3
4
5
6
7
8
9

In [12]: for i in range(10):
    ...:   print i 
    ...:   
0
1
2
3
4
5
6
7
8
9

In [13]: for i in range(1, 10)
  File "<ipython-input-13-e76dcc18ea23>", line 1
    for i in range(1, 10)
                         ^
SyntaxError: invalid syntax


In [14]: for i in range(1, 10):
    ...:     print i
    ...:     
1
2
3
4
5
6
7
8
9

In [15]: for i in range(1, 11):
    ...:     print i
    ...:     
1
2
3
4
5
6
7
8
9
10

In [16]: for i in range(1, 11):
    ...:     print i
    ...:     
1
2
3
4
5
6
7
8
9
10

In [17]: 

In [17]: lenList = 10

In [18]: for in range(1, lenList+1)
  File "<ipython-input-18-7252cc81e70f>", line 1
    for in range(1, lenList+1)
         ^
SyntaxError: invalid syntax


In [19]: for in range(1, lenList+1):
  File "<ipython-input-19-35c5ab053ad9>", line 1
    for in range(1, lenList+1):
         ^
SyntaxError: invalid syntax


In [20]: for in range(1, lenList+1):
  File "<ipython-input-20-35c5ab053ad9>", line 1
    for in range(1, lenList+1):
         ^
SyntaxError: invalid syntax


In [21]: for i in range(1, lenList+1):
    ...:     print i 
    ...:     
1
2
3
4
5
6
7
8
9
10

In [22]: for i in range(5, lenList+1):
    ...:     print i 
    ...:     
5
6
7
8
9
10

In [23]: for i in range(1, lenList+1, 2):
    ...:     print i 
    ...:     
1
3
5
7
9

In [24]: x = True

In [25]: 

In [25]: x == False
Out[25]: False

In [26]: x == True
Out[26]: True

In [27]: x > 1
Out[27]: False

In [28]: x < 1
Out[28]: False

In [29]: x == True 
Out[29]: True

In [30]: x = 7

In [31]: x > 15
Out[31]: False

In [32]: x == 7
Out[32]: True

In [33]: x != 7
Out[33]: False

In [34]: IS NOT 
  File "<ipython-input-34-21c68e524d39>", line 1
    IS NOT
         ^
SyntaxError: invalid syntax


In [35]: 

In [35]: x = [['Danny',34],['Mary',50]]

In [36]: x[0]
Out[36]: ['Danny', 34]

In [37]: x[1]
Out[37]: ['Mary', 50]

In [38]: x[0][1]
Out[38]: 34

In [39]: x = {'name':Danny, 'age': 34}
-----------------------------------------------------------------------
NameError                             Traceback (most recent call last)
<ipython-input-39-2ff853b8f525> in <module>()
----> 1 x = {'name':Danny, 'age': 34}

NameError: name 'Danny' is not defined

In [40]: x = {'name':'Danny', 'age': 34}

In [41]: x[name]
-----------------------------------------------------------------------
NameError                             Traceback (most recent call last)
<ipython-input-41-24cb1f451142> in <module>()
----> 1 x[name]

NameError: name 'name' is not defined

In [42]: x = {'name':'Danny'; 'age': 34}
  File "<ipython-input-42-0c5ea1e5b97e>", line 1
    x = {'name':'Danny'; 'age': 34}
                       ^
SyntaxError: invalid syntax


In [43]: x = {'name':'Danny'}

In [44]: x['name']
Out[44]: 'Danny'

In [45]: x = {{'name':'Danny','age': 34}}
-----------------------------------------------------------------------
TypeError                             Traceback (most recent call last)
<ipython-input-45-f429c0801fc3> in <module>()
----> 1 x = {{'name':'Danny','age': 34}}

TypeError: unhashable type: 'dict'

In [46]: x[name]
-----------------------------------------------------------------------
NameError                             Traceback (most recent call last)
<ipython-input-46-24cb1f451142> in <module>()
----> 1 x[name]

NameError: name 'name' is not defined

In [47]: x = {'name':'Danny'}

In [48]: x[name]
-----------------------------------------------------------------------
NameError                             Traceback (most recent call last)
<ipython-input-48-24cb1f451142> in <module>()
----> 1 x[name]

NameError: name 'name' is not defined

In [49]: x[name]
-----------------------------------------------------------------------
NameError                             Traceback (most recent call last)
<ipython-input-49-24cb1f451142> in <module>()
----> 1 x[name]

NameError: name 'name' is not defined

In [50]: x = {'name':'Danny'}

In [51]: x['name']
Out[51]: 'Danny'

In [52]: x = {'name':'Danny','location':'brooklyn','glasses':True}

In [53]: x
Out[53]: {'glasses': True, 'location': 'brooklyn', 'name': 'Danny'}

In [54]: x['location']
Out[54]: 'brooklyn'

In [55]: x['name']
Out[55]: 'Danny'

In [56]: x[]
  File "<ipython-input-56-0a34b3b9ccfd>", line 1
    x[]
      ^
SyntaxError: invalid syntax


In [57]: x['glasses']
Out[57]: True

In [58]: x = 'Danny'

In [59]: x.lower()
Out[59]: 'danny'

In [60]: x.upper()
Out[60]: 'DANNY'

In [61]: myList = ['BROADWAY','Havermaeryer','MAin St.',"1234"]

In [62]: for i in myList:
    ...:     print i.lower()
    ...:     
broadway
havermaeryer
main st.
1234

In [63]: for i in myList:
    ...:     print i.upper()
    ...:     
    ...:     
BROADWAY
HAVERMAERYER
MAIN ST.
1234

In [64]: 

In [64]: 

```

**Comment by nygeog** [comment]
Closing this, repointing to this from lecture if anyone wants to review
